### ISSUE TITLE
The Redirection Doorhanger is not displayed when navigating a default-made AMO search engine's homepage

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mikedeboer/shield-search-nudges#23]
[Affected versions]:
- Firefox release Version 61.0.2
- Nightly Version 63.0a1

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- The "extensions.shield-search-nudges.variation" boolean pref is set to "doshow".
- Doorhanger Nudges version 1.4.0 addon is available.
- Google.de is installed from [here](https://addons.mozilla.org/en-US/firefox/addon/googlede/?src=search) and set as a default Search Engine.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and install the Doorhanger Nudges addon. 
2. Restart the browser.
2. Navigate to "google.de" and observe the behavior.

[Expected result]:
- The Redirection doorhanger is displayed.

[Actual result]:
- The Redirection doorhanger is not displayed.

[Additional Notes]:
- The issue is also reproducible on the following search engines: Ask, Baidu, Yandex, Internet Archive, Yahoo.com.
- On YouTube(SSL) the doorhanger appears correctly.
- I have attached a screen recording of the issue:
![no doorhanger](https://user-images.githubusercontent.com/40393891/43965124-252a9bda-9cc7-11e8-9d9f-7cdf29786801.gif)

**Comment by Standard8** [comment]
I think this is a duplicate / same as #12 - there's various conditions where going to a search engine has extra query parameters, so won't match out search, e.g. visiting `yahoo.com` I get redirected to an acknowledgement page, then to `https://uk.yahoo.com/?p=us&guccounter=1`

Looks like we need to do a more complicated matching...

**Comment by Standard8** [comment]
From #23, `google.com` goes to `https://www.google.com/?gws_rd=ssl` in private browsing mode.

**Comment by Softvision-PatriciuPop** [comment]
This issue is also reproducible on the Wikipedia and Bing default search engines. For Bing the user is redirected to "https://www.bing.com/?toWww=1&redig=32177FB59AE945FF944024F304AAE1E6" and for Wikipedia, "https://en.wikipedia.org/wiki/Main_Page". Also "https://www.wikipedia.org/" did not trigger the doorhanger either. On Bing we managed to work around it by writing the "www.bing.com" URL manually or by copy pasting it.

**Comment by mikedeboer** [comment]
This was fixed in 6d9286c7fc012f5bdab6521101fec0c9fd6fa700

**Comment by Softvision-PatriciuPop** [comment]
I have verified this issue using the latest Search Nudges version 1.5.1 and it's still reproducible on various search engines including: Yandex, Wikipedia and Ask. Tested on Windows 10 x64, Mac 10.13.6 and Arch Linux 4.12. 
Considering this, the issue should be reopened.

**Comment by mikedeboer** [comment]
I'm not going to do that, if it works for the other main search engines that we currently ship with. Because that's what we're targeting with this study - more robust URL pattern checking will be necessary when this code ends up shipping in Firefox.

**Comment by Softvision-PatriciuPop** [comment]
The behavior has been improved, since this issue is not reproducible on Bing (default search engine). But the issue is still reproducible for Wikipedia (EN), which is also a default search engine. Do you think we can fix the issue for Wikipedia as well?

**Comment by SoftVision-CosminMuntean** [comment]
From what I understand the study is targeting the main search engines that are available in the browser, but this issue is still reproducible for Wikipedia (EN), which is a default search engine.

The "General Onboarding" tip is correctly displayed when open a new tab. But, the "Redirect" tip is not displayed if you navigate to "https://en.wikipedia.org" or "https://en.wikipedia.org/wiki/Main_Page".
Here is a screen recording with the issue:
![wikipedia redirect tip](https://user-images.githubusercontent.com/19226534/44394147-2cec3380-a53f-11e8-9ae5-4a63612fc672.gif)


Considering this I will reopen the issue until a decision is made about this.

**Comment by mikedeboer** [comment]
The redirects that wikipedia does is different from the other engines and not something we'd like to address for the study. This is something we'll address once this study informs us that this feature should be in-product.
